### ISSUE TITLE
wxService redis 配置共享问题

### ISSUE THREAD

**Issue by liangzhiyuan2015** [binarywang/weixin-java-mp-demo-springboot#100]
作者你好，我看了一下 3.8最新的文档 关于 配置provider

WxMpRedisConfigImpl | 基于Redis的微信配置provider.
-- | --
`// 默认缓存在内存中，配置redis就放入redis中 
WxMpDefaultConfigImpl configStorage = !redisIsOk() ? new WxMpDefaultConfigImpl() : new WxMpRedisConfigImpl(jedisPool);`
本地的redis 好像没存入 微信公众号配置的相关信息。
不知道 我是不是 哪里操作有误！谢谢！

**Comment by binarywang** [comment]
那个实现的redis存储类，只是存储access_token用的，用于多台服务器共享token，其他信息你如果需要共享，需要自己实现

**Comment by liangzhiyuan2015** [comment]
好的，理解了！谢谢哦！
