### ISSUE TITLE
不清楚是在哪里调用的接口？

### ISSUE THREAD

**Issue by youhongPeng** [binarywang/weixin-java-mp-demo-springboot#14]
开始我的疑问是当用户给公众号发送消息，回复消息时没看到在哪里调用了接口，后来我重新看了一下微信官方文档，发现回复内容不需要调用接口

**Comment by youhongPeng** [comment]
开始我的疑问是当用户给公众号发送消息，回复消息时没看到在哪里调用了接口，后来我重新看了一下微信官方文档，发现回复内容不需要调用接口

**Comment by binarywang** [comment]
建议自己跟踪调试下代码。同步回复消息不需要调接口，直接回复给微信的是报文
