### ISSUE TITLE
返回的消息出现中文乱码

### ISSUE THREAD

**Issue by xiaohui1016** [binarywang/weixin-java-mp-demo-springboot#16]
![06 5 x4pk1gswk4 jo1 5](https://user-images.githubusercontent.com/21259643/42633926-6cd8d862-8614-11e8-96cd-1b9b7d46931c.png)

 յ   Ϣ   ݣ {"toUser":"gh_50e96c98ff7e","fromUser":"oEEdZ1JuWWyDmOrntPFj-BjtC9s0","createTime":1531399215,"msgType":"text","content":"    ","msgId":6577309546223567809,"scanCodeInfo":{},"sendPicsInfo":{"picList":[]},"sendLocationInfo":{},"hardWare":{}}
这是乱码的数据

**Comment by binarywang** [comment]
你的截图中并没看到乱码，不知道你说的乱码文字是哪里出现的

**Comment by xiaohui1016** [comment]
接收到的没乱码，回复之后就乱码了

**Comment by xiaohui1016** [comment]
乱码问题解决了，设置编码设置成gbk了，改成utf-8就好了
