### ISSUE TITLE
请问如何获得unionId

### ISSUE THREAD

**Issue by smile-yan** [binarywang/weixin-java-mp-demo-springboot#31]
新年快乐！binarywang !
发现源码中并没有提供获得unionId的方法，请问我应该怎么解决呢？

**Comment by smile-yan** [comment]
哦哦，明白了，好像必须是微信公众平台认证后才可以。
要交三百块起，提交相关文档然后才可以通过认证。

**Comment by binarywang** [comment]
unionid应该是获取用户信息接口里返回的
