### ISSUE TITLE
如何将sdk加到一个已有的项目中？

### ISSUE THREAD

**Issue by bolinli** [binarywang/weixin-java-mp-demo-springboot#37]
直接用jar包依赖的方式会导致已有的tomcat被覆盖，请问该怎么融合呢？

**Comment by binarywang** [comment]
不知道你说的啥意思，请使用maven依赖，如果不懂先学习下

**Comment by bolinli** [comment]
> 不知道你说的啥意思，请使用maven依赖，如果不懂先学习下

我用的是springcloud项目 加入wxjava这个依赖，然后使用@EnableConfigurationProperties和属性文件配置公众号相关的信息，发现配置文件被覆盖了，本来我的项目是8020，引入依赖之后变为了8080，不知道什么原因？

**Comment by binarywang** [comment]
那你没先跑下本demo看看吗？

**Comment by bolinli** [comment]
已经跑过了，能够正常运行，但是我想把wxjava的依赖加到自己的项目中去用，参照的就是demo的使用方式


------------------ 原始邮件 ------------------
发件人: "Binary Wang"<notifications@github.com>;
发送时间: 2019年3月6日(星期三) 下午2:57
收件人: "binarywang/weixin-java-mp-demo-springboot"<weixin-java-mp-demo-springboot@noreply.github.com>;
抄送: "淡忘う诠释着一切"<1074670234@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [binarywang/weixin-java-mp-demo-springboot] 如何将sdk加到一个已有的项目中？ (#37)




那你没先跑下本demo看看吗？

**Comment by binarywang** [comment]
那你自己对比看看你自己实现的有什么不同，不就清楚问题所在了吗？
