### ISSUE TITLE
添加图文素材的时候正文怎么插入音频是视频

### ISSUE THREAD

**Issue by WNavy** [binarywang/weixin-java-mp-demo-springboot#39]

**Comment by binarywang** [comment]
看不懂啥意思，写错了什么字吗？

**Comment by WNavy** [comment]
哦哦,是写错了，我的意思是上传永久图文信息的时候，在富文本里面插入音频和视频，用的是<video><audio>这两标签，但是上传之后，微信自动过滤了这两个标签，所以图文里面的视频和音频都不显示，现在要解决这个问题




------------------ 原始邮件 ------------------
发件人: "Binary Wang"<notifications@github.com>;
发送时间: 2019年3月14日(星期四) 下午3:07
收件人: "binarywang/weixin-java-mp-demo-springboot"<weixin-java-mp-demo-springboot@noreply.github.com>;
抄送: "Jun"<826818399@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [binarywang/weixin-java-mp-demo-springboot] 添加图文素材的时候正文怎么插入音频是视频 (#39)




看不懂啥意思，写错了什么字吗？

**Comment by WNavy** [comment]
你上传永久图文素材试过添加语音么？

**Comment by shijie32177** [comment]
严重问题
java.lang.RuntimeException: java.net.SocketException: Connection reset
getAccessToken报错了 用httpUrlConnection单独调用微信接口是可以请求的
