### ISSUE TITLE
项目启动后获取不到菜单

### ISSUE THREAD

**Issue by HD534** [binarywang/weixin-java-mp-demo-springboot#40]
Hi binary，感谢你的demo。我启动后有个问题，微信公众号端获取不到菜单。
菜单的创建时在这个controller下面的吧?com.github.binarywang.demo.wx.mp.controller.WxMenuController，
我修改了@GetMapping("/create") 下面的菜单内容而已。
客户端发送信息能收到服务端返回的消息。
是需要其他的配置吗？

**Comment by binarywang** [comment]
你调用过这个接口吗？

**Comment by HD534** [comment]
没有手动调用这个接口；关注公众号，微信是会主动发送请求去获取菜单吧?
是由于这个mapping不是微信获取menu 的那个url吗？

**Comment by binarywang** [comment]
那你认为谁会去调用你这个接口，如果你自己不去调用的话？

**Comment by binarywang** [comment]
菜单需要你自己通过某种动作去触发生成，而且是一次性的，生成以后，菜单就存储在微信服务器上的，建议仔细阅读下官方相关文档

**Comment by HD534** [comment]
好的，谢谢你的解答。
