### ISSUE TITLE
网页授权报错 报空指针

### ISSUE THREAD

**Issue by dydyg** [binarywang/weixin-java-mp-demo-springboot#44]
![图片](https://user-images.githubusercontent.com/40195323/56643493-4fc17f80-66ac-11e9-906d-29f7e0897e52.png)
![图片](https://user-images.githubusercontent.com/40195323/56643573-74b5f280-66ac-11e9-829b-ddb0782fe6e1.png)
消息交互可以，网页授权不行。不明白

**Comment by binarywang** [comment]
空指针了，你还不明白？自己调试分析下是哪儿导致的？

**Comment by dydyg** [comment]
,知道了。貌似要把这个多余部分的配置删除掉，才可以进行网页授权。


------------------ 原始邮件 ------------------
发件人: "Binary Wang"<notifications@github.com>;
发送时间: 2019年4月24日(星期三) 下午5:46
收件人: "binarywang/weixin-java-mp-demo-springboot"<weixin-java-mp-demo-springboot@noreply.github.com>;
抄送: "Y逸.G仙 DA!"<1454109713@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [binarywang/weixin-java-mp-demo-springboot] 网页授权报错 报空指针 (#44)




空指针了，你还不明白？自己调试分析下是哪儿导致的？
