### ISSUE TITLE
全局的access_token跟获取用户详细信息的access_token的区分

### ISSUE THREAD

**Issue by aliguyoyo** [binarywang/weixin-java-mp-demo-springboot#47]
[https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140842](url)

access_token | 网页授权接口调用凭证,注意：此access_token与基础支持的access_token不同
这个是获取用户详细信息的access_token,跟系统级的access_token是不一样的，问题就出在代码里封装了post跟get请求，强制把基础支持的access_token加上了，这样在拉取用户信息(需scope为 snsapi_userinfo)：http：GET（请使用https协议） https://api.weixin.qq.com/sns/userinfo?access_token=ACCESS_TOKEN&openid=OPENID&lang=zh_CN时会有问题吧

**Comment by binarywang** [comment]
搞啥呢？
