### ISSUE TITLE
wxService.switchover(mpId) 疑问

### ISSUE THREAD

**Issue by analyzesm** [binarywang/weixin-java-mp-demo-springboot#50]
@Bean
    public WxMpService wxMpService() {
        // 代码里 getConfigs()处报错的同学，请注意仔细阅读项目说明，你的IDE需要引入lombok插件！！！！
        final List<WxMpProperties.MpConfig> configs = this.properties.getConfigs();
        if (configs == null) {
            throw new RuntimeException("大哥，拜托先看下项目首页的说明（readme文件），添加下相关配置，注意别配错了！");
        }

        WxMpService service = new WxMpServiceImpl();
        service.setMultiConfigStorages(configs
            .stream().map(a -> {
                WxMpInMemoryConfigStorage configStorage = new WxMpInMemoryConfigStorage();
                configStorage.setAppId(a.getAppId());
                configStorage.setSecret(a.getSecret());
                configStorage.setToken(a.getToken());
                configStorage.setAesKey(a.getAesKey());
                return configStorage;
            }).collect(Collectors.toMap(WxMpInMemoryConfigStorage::getAppId, a -> a, (o, n) -> o)));
        return service;
    }

这里有一个疑问，既然 service.setMultiConfigStorages 没有配置MpId的地方
为什么 wxService.switchover(mpId) ？

**Comment by binarywang** [comment]
仔细阅读下源码，看看mpId是什么意思

**Comment by analyzesm** [comment]
发消息如果不用这种方式，return new TextBuilder().build(content, wxMessage, weixinService);
消息传递过来不是有mpid 吗，那怎么切换为指定的 WxMpService 呢

我看了您的菜单Controller，这里 wxService.switchover(mpId) 传递了 appid

**Comment by binarywang** [comment]
你仔细阅读下源码不就清楚了吗，mpId是对应于公众号帐号的标识，可以使用appid，也可以自定义
