### ISSUE TITLE
获取jsapi_ticket后在 微信 JS 接口签名校验工具 上测试签名不一致

### ISSUE THREAD

**Issue by 465255696** [binarywang/weixin-java-mp-demo-springboot#52]
获取jsapi_ticket后在 微信 JS 接口签名校验工具 上测试签名不一致

**Comment by 465255696** [comment]
调取微信JSSDK接口，需要获取签名
/**
     * 获得配置信息
     * @param url
     * @return Result
     */
    @GetMapping("getConfig")
    public Result getConfig(String url){
        try {
            WxJsapiSignature jsapiSignature = wxMpService.createJsapiSignature(url);
            Map<String, Object> map = new HashMap<>(4);
            map.put("timestamp", jsapiSignature.getTimestamp());
            map.put("nonceStr", jsapiSignature.getNonceStr());
            map.put("signature", jsapiSignature.getSignature());
            map.put("appId", jsapiSignature.getAppId());
            return Result.result(map);
        } catch (WxErrorException e) {
            e.printStackTrace();
        }
        return null;
    }
调用如上接口，生成的signature与微信上边生成的不一致，导致签名失效无法调用jssdk，请问这是为什么呢？是signature的加密算法不一样？

**Comment by 465255696** [comment]
今天重新调用接口，在debug上发现后台请求了票据，第二次再调用就不在请求票据了，请问票据是被缓存起来了吗？缓存在哪里了呢？

**Comment by binarywang** [comment]
签名不一致，你仔细检查下是不是参数名不对。至于ticket的问题，自己看源码即可，这又不是闭源的东西。
