### ISSUE TITLE
WxMpConfiguration 示例代码中消息路由规则错误

### ISSUE THREAD

**Issue by mirocolo** [binarywang/weixin-java-mp-demo-springboot#53]
messageRouter()方法中
点击菜单连接事件中消息类型错误   示例代码用的是
me.chanjar.weixin.common.api.WxConsts.MenuButtonType.CLICK
正确的应该是
me.chanjar.weixin.common.api.WxConsts.EventType.CLICK
点击菜单连接事件也是如此
代码中为
me.chanjar.weixin.common.api.WxConsts.MenuButtonType.VIEW
正确的是
me.chanjar.weixin.common.api.WxConsts.EventType.VIEW

**Comment by binarywang** [comment]
这个问题不大，都是字符串类型的

**Comment by mirocolo** [comment]
两个字符串很相似但大小写不一样，会导致事件匹配不上 。。 当然打开微信调试模式对比微信文档来看 很快能发现这个问题

**Comment by binarywang** [comment]
> 两个字符串很相似但大小写不一样，会导致事件匹配不上 。。 当然打开微信调试模式对比微信文档来看 很快能发现这个问题

你确定？路由匹配代码不区分大小写的

**Comment by mirocolo** [comment]
看你源码，路由器规则中是不区分大小写 但是你写的示例handler中有用到
com.github.binarywang.demo.wx.mp.handle.MenuHandler这里面用的也是me.chanjar.weixin.common.api.WxConsts.MenuButtonType.VIEW,但是却和消息的type做了比对（第28行代码）

但我是因为参照demo的这个写法没有进入到想进入的handler，反而走入了最后一个日志handler，才发现这个问题

**Comment by mirocolo** [comment]
找了下历史代码，路由器匹配规则没问题，应该就是handler中比对类型没有像路由时忽略大小写导致没有实现我自己的规则

**Comment by binarywang** [comment]
> 找了下历史代码，路由器匹配规则没问题，应该就是handler中比对类型没有像路由时忽略大小写导致没有实现我自己的规则

这确实是个问题，那个代码有点问题，已修复
