### ISSUE TITLE
多应用情况下出现系统奔溃

### ISSUE THREAD

**Issue by champion97** [binarywang/weixin-java-mp-demo-springboot#55]
参照此demo实现了多个appid切换的功能，但部署上线后，频繁出现系统崩溃，出现以下日志：

Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: unable to create new native thread

版本v3.4.0

btw 线上环境，问题紧急希望有大佬帮忙看看，可提供样本。

**Comment by binarywang** [comment]
请提供详细日志

**Comment by kareanyi** [comment]
顺便提供一下服务器配置情况，几台机子 什么配置

**Comment by champion97** [comment]
> 请提供详细日志
> 顺便提供一下服务器配置情况，几台机子 什么配置

谢谢，我自己代码问题，已解决。
