### ISSUE TITLE
WXMP demo启动不了，我安装了lombok插件了

### ISSUE THREAD

**Issue by chenglegit** [binarywang/weixin-java-mp-demo-springboot#56]
读不到我的yml文件的配置
![image](https://user-images.githubusercontent.com/48047435/65652094-39489700-e043-11e9-9fbf-1a2914f8e410.png)

![image](https://user-images.githubusercontent.com/48047435/65652116-49607680-e043-11e9-9e9e-7b554ab00220.png)
![image](https://user-images.githubusercontent.com/48047435/65652136-5e3d0a00-e043-11e9-961d-4410273405f0.png)
我也构建了多次，lombok插件早就安装过了 其他项目都是可以启动的

**Comment by chenglegit** [comment]
properties 文件
![image](https://user-images.githubusercontent.com/48047435/65652871-d5739d80-e045-11e9-92d5-429e0aa3dcaa.png)

**Comment by binarywang** [comment]
读不到配置跟lombok没关系，自己仔细对比检查下哪里写错了
