### ISSUE TITLE
怎么上传图片到微信服务器，再通过mediaId获取到这张图片；另外怎么再handler里访问WxMpService类

### ISSUE THREAD

**Issue by lyq1** [binarywang/weixin-java-mp-demo-springboot#68]

**Comment by binarywang** [comment]
能否看下wxjava的wiki文档？结合微信的官方文档一起看。

handler里的方法里不时有WxMpService的参数吗？

**Comment by lyq1** [comment]
> 能否看下wxjava的wiki文档？结合微信的官方文档一起看。
> 
> handler里的方法里不是有WxMpService的参数吗？

大佬，wiki文档在哪

**Comment by binarywang** [comment]
请仔细看下首页说明，已经说的很详细了吧
