### ISSUE TITLE
没有看到注入地方，为什么也能 this 调用？

### ISSUE THREAD

**Issue by zjxpcyc** [binarywang/weixin-java-mp-demo-springboot#70]
[#L28](https://github.com/binarywang/weixin-java-mp-demo-springboot/blob/master/src/main/java/com/github/binarywang/demo/wx/mp/controller/WxMenuController.java#L28) 行为啥 没有注入，也可以直接 this.wxService 用? 请大神解惑下

**Comment by binarywang** [comment]
spring 构造方法注入了解下？
