### ISSUE TITLE
如何更改默认的8080端口?

### ISSUE THREAD

**Issue by zzyyzz1992** [binarywang/weixin-java-mp-demo-springboot#74]
希望可以自定义端口,找不到可以更改的地方.
希望自定义端口后使用nginx映射,不能自定义很难受!

**Comment by zzyyzz1992** [comment]
server:
    port: 8021
https://mkyong.com/spring-boot/spring-boot-how-to-change-tomcat-port/

**Comment by binarywang** [comment]
。。。
