### ISSUE TITLE
微信登录失败，redirect_uri域名与后台配置不一致

### ISSUE THREAD

**Issue by justry2013** [binarywang/weixin-java-mp-demo-springboot#75]
按照demo get方式请求 /wx/menu/{appid}/create方式创建菜单执行成功，点击获取用户信息菜单，提示微信登录失败，redirect_uri域名与后台配置不一致。 看日志输出的url和后台设置的域名是一样的啊。

**Comment by binarywang** [comment]
仔细看下官方配置说明，应该是你某个地方配置错误
