### ISSUE TITLE
发送文本消息异常：api.weixin.qq.com:443 failed to respond

### ISSUE THREAD

**Issue by thouthout** [binarywang/weixin-java-mp-demo-springboot#77]
@binarywang 您好，
       我使用3.6.0版本给微信发送文本消息的时候，偶尔会报如下错误 “api.weixin.qq.com:443 failed to respond”   报警类是：me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl，请问下这是什么问题那？

**Comment by binarywang** [comment]
这个应该是超时了，按照wxjava里的wiki里的相关文档说明增加下相关超时参数值

**Comment by thouthout** [comment]
@binarywang 把超时时间设置长了，已经好几天没有报过这个错了，看来就是这个原因，感谢您的解答

**Comment by friends110110** [comment]
@thouthout 请问下具体是怎么设置的？
