### ISSUE TITLE
该公众号提供的服务出现的故障，请稍候再试

### ISSUE THREAD

**Issue by formerce** [binarywang/weixin-java-mp-demo-springboot#79]
/wechat/portal处理被动回复消息时返回“success"，公众号出现该公众号提供的服务出现的故障，请稍候再试。
代码如下：
 @ResponseBody
    @PostMapping(produces = "application/xml; charset=UTF-8")
    public String post(@RequestBody String requestBody, @RequestParam("signature") String signature,
                       @RequestParam(name = "encrypt_type", required = false) String encType,
                       @RequestParam(name = "msg_signature", required = false) String msgSignature,
                       @RequestParam("timestamp") String timestamp, @RequestParam("nonce") String nonce) {
        try {
            this.logger.info(String.format("\n接收微信请求：[signature=[{%s}], encType=[{%s}], msgSignature=[{%s}],"
                            + " timestamp=[{%s}], nonce=[{%s}], requestBody=[\n{}\n] ",
                    signature, encType, msgSignature, timestamp, nonce, requestBody));

            if (!this.wxService.checkSignature(timestamp, nonce, signature)) {
                throw new IllegalArgumentException("非法请求，可能属于伪造的请求！");
            }

            String out = null;
            if (encType == null) {
                // 明文传输的消息
                WxMpXmlMessage inMessage = WxMpXmlMessage.fromXml(requestBody);
                WxMpXmlOutMessage outMessage = this.wxService.route(inMessage);

                //新增菜单消息逻辑，为了和CMS兼容（CMS是直接保存的xml数据，不需要再转对象，直接读出来替换占位符后就返回）
               /* if (WxConsts.EventType.CLICK.equals(inMessage.getEvent())) {
                    out = menuHandler.click(inMessage, wxService);
                    this.logger.debug("\n组装回复信息：{}", out);
                    return out;
                }*/
                if (outMessage == null) {
                    return "success";
                }

                out = outMessage.toXml();
            } else if ("aes".equals(encType)) {
                // aes加密的消息
                WxMpXmlMessage inMessage = WxMpXmlMessage.fromEncryptedXml(requestBody,
                        this.wxService.getWxMpConfigStorage(), timestamp, nonce, msgSignature);
                this.logger.debug("\n消息解密后内容为：\n{} ", inMessage.toString());
                WxMpXmlOutMessage outMessage = this.wxService.route(inMessage);
                if (outMessage == null) {
                    return "success";
                }

                out = outMessage.toEncryptedXml(this.wxService.getWxMpConfigStorage());
            }

            this.logger.debug("\n组装回复信息：{}", out);

            return out;
        } catch (Throwable t) {
            logger.error("微信消息回复异常", t);
            return null;
        }
    }

**Comment by binarywang** [comment]
代码格式看起来有点乱，你对照demo看下，看哪里改动导致有影响？
