### ISSUE TITLE
wxMpService.getJsapiTicket();空指针异常

### ISSUE THREAD

**Issue by wzq530897296** [binarywang/weixin-java-mp-demo-springboot#83]
调用这个方法有空指针异常，token可以获取到。官网里面说用token获取ticket，这个不用吗？

**Comment by binarywang** [comment]
具体代码和错误信息看不到，无法定位问题。
建议自行debug查看问题根源，空指针问题其实最容易定位问题原因了

**Comment by wzq530897296** [comment]
找到问题了，我把service注入了两次，还用了两次。。。。。眼神有问题。。。。
