### ISSUE TITLE
添加了lombok，运行时不能识别get方法

### ISSUE THREAD

**Issue by tenyears94** [binarywang/weixin-java-mp-demo-springboot#84]
项目中添加了lombok依赖，IDEA添加了lombok插件，但是经常会出现找不到get方法的错误，重新直接运行也会出现这个错误，只能先删除target才能重新编译。

** 百度上现有的方法都尝试了，还是不能解决

**Comment by binarywang** [comment]
自己手动生成相关方法吧，你这种问题我还真没遇到过
