### ISSUE TITLE
多个公众号问题

### ISSUE THREAD

**Issue by shenyafang** [binarywang/weixin-java-mp-demo-springboot#86]
配置了多个公众号时，发模板消息报错
@Override
  public WxMpConfigStorage getWxMpConfigStorage() {
    if (this.configStorageMap.size() == 1) {
      // 鍙湁涓�涓叕浼楀彿锛岀洿鎺ヨ繑鍥炲叾閰嶇疆鍗冲彲
      return this.configStorageMap.values().iterator().next();
    }

    return this.configStorageMap.get(WxMpConfigStorageHolder.get());
  }

this.configStorageMap.size()不等于1，所以
 @Override
    public String getUrl(WxMpConfigStorage config) {
      return buildUrl(config.getHostConfig(), prefix, path);
    }
config为空，所以在多个公众号发模板消息时，怎么确定给哪个公众号发消息？
绑定公众号的appid在哪传递？

**Comment by binarywang** [comment]
你是怎么配置的？是否参考过demo？

**Comment by binarywang** [comment]
没看懂，你的代码是怎么写的？为什么config为空

**Comment by shenyafang** [comment]
我粘的都是源代码，config为空是因为configStorageMap这个里面有两个公众号，所有它返回的是
return this.configStorageMap.get(WxMpConfigStorageHolder.get());至于两个configStorageMap的size大于1时，为啥返回空也是我想问的，还有就是我看3.0的版本和3.7的版本，WxMpTemplateMessage这个类，及发送模板消息的方法是一样的，并没有因为引入多公众号功能发生改变，所以我想问，在发送模板消息时怎么区别是哪个公众号

**Comment by shenyafang** [comment]
我找到了发送模板消息之前，设置当前公众号的那个接口了，非常感谢
