### ISSUE TITLE
设置了代理地址之后400的错误

### ISSUE THREAD

**Issue by Zxxjgp** [binarywang/weixin-java-mp-demo-springboot#90]
错误代码：0, 错误信息：status code: 400, reason phrase: Bad Request、
![image](https://user-images.githubusercontent.com/26613713/83879797-cdd9cc00-a770-11ea-849c-91120289336d.png)

**Comment by binarywang** [comment]
你的代理确定没问题吗？

**Comment by Zxxjgp** [comment]
是我代理的问题、不好意思、搞错了、打扰您了
