### ISSUE TITLE
是否关注公众号属性subscribe为空

### ISSUE THREAD

**Issue by kangxinli** [binarywang/weixin-java-mp-demo-springboot#91]
WxMpUser user = wxService.oauth2getUserInfo(accessToken, null);
user.getSubscribe() == null

**Comment by binarywang** [comment]
看下微信的返回原始报文是什么

**Comment by kangxinli** [comment]
返回WxMpUser只有这些字段，不管有没有关注公众号，subscribe都获取不到{"openId":"","nickname":"","sexDesc":"","sex":1,"language":"zh_CN","city":"","province":"","country":"","headImgUrl":"","unionId":"","privileges":[]}

**Comment by binarywang** [comment]
看来微信确实没有给返回，那就没办法
