### ISSUE TITLE
在配置多公众号的时候，是否可以动态加载数据库中配置新的公众号信息进来，Java服务不用重启？

### ISSUE THREAD

**Issue by liangzhiyuan2015** [binarywang/weixin-java-mp-demo-springboot#92]
hi，作者你好！
我的问题描述是：我已经创建了一个数据库表：mp_setting

- `CREATE TABLE `mp_setting` (
-   `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '[id]',
-   `create_dtm` datetime DEFAULT current_timestamp() COMMENT '[创建时间]',
-   `del` int(2) DEFAULT 0 COMMENT '[逻辑删除]{0:未删;1:已删}',
-   `del_dtm` datetime DEFAULT NULL COMMENT '[删除时间]',
-   `update_dtm` datetime DEFAULT NULL ON UPDATE current_timestamp() COMMENT '[更新时间]',
-   `appid` varchar(255) DEFAULT NULL COMMENT '[微信公众号AppID]',
-   `app_secret` varchar(255) DEFAULT NULL COMMENT '[微信公众号AppSecret]',
-   `host` varchar(300) DEFAULT NULL COMMENT '[域名地址]',
-   `mp_id` int(11) DEFAULT NULL COMMENT '[公众号序号]',
-   PRIMARY KEY (`id`) USING BTREE
- ) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;`

然后，进行了公众号相关的配置
`@AllArgsConstructor
@Configuration
public class WxMpConfiguration {

    @Autowired
    private MpSettingService mpSettingService;

    @Bean
    public WxMpService wxMpService() {
        MpSetting model = new MpSetting();
        List<MpSetting> list = mpSettingService.findAll(model);
        if (null == list) {
            throw new RuntimeException("请添加公众号相关配置,注意别配错了！");
        }
        WxMpService service = new WxMpServiceImpl();
        // 公众号信息缓存起来
        service.setMultiConfigStorages(list
                .stream().map(a -> { // 根据list读取公众号参数配置,这里可以从配置文件、数据库、缓存任意一个源读取
                    WxMpDefaultConfigImpl configStorage = new WxMpDefaultConfigImpl();
                    // 设置公众号参数
                    configStorage.setAppId(a.getAppID());
                    configStorage.setSecret(a.getAppSecret());
                    return configStorage;
                }).collect(Collectors.toMap(WxMpDefaultConfigImpl::getAppId, a -> a, (o, n) -> o)));
        return service;
    }

    @Bean
    public WxMpMessageRouter messageRouter(WxMpService wxMpService) {
        final WxMpMessageRouter newRouter = new WxMpMessageRouter(wxMpService);
        return newRouter;
    }

}`

最后，在controller层

> @ApiOperation("微信公众号网页授权")
    @GetMapping("/mpAuthorize/{appid}")
    public String mpAuthorize(@PathVariable String appid, @RequestParam String returnUrl) {
        **switchover(appid);**
        MpSetting model = mpSettingService.findByAppIDAndDel(appid);
        if (null == model) {
            throw new IllegalArgumentException(String.format("未找到对应appid=[%s]的配置，请核实！", model.getAppID()));
        }
        String url = model.getHost() + "/client/wechat/mpAuthorizeNotify";
        String redirectUrl = this.wxService.oauth2buildAuthorizationUrl(url, WxConsts.OAuth2Scope.SNSAPI_USERINFO, URLEncoder.encode(returnUrl));
        log.info("【微信公众号网页授权】redirectUrl={}", redirectUrl);
        return "redirect:" + redirectUrl;
    }

> private void switchover(String appid) {
        if (!this.wxService.switchover(appid)) {
            _throw new IllegalArgumentException(String.format("未找到对应appid=[%s]的配置，请核实！", appid));_
        }
    }

程序第一次运行后是没问题的；但是当我再次需要在数据库表`mp_setting`新增一行公众号信息的时候，没有立刻重启Java服务，在微信浏览器上输入，http://公网可访问域名/xx/mpAuthorize/wx279xx3c3dxxxxx 就会发生异常：**未找到对应appid=[wx279xx3c3dxxxxx]的配置，请核实！]**；接着我重启一下Java服务，数据库上的配置信息就加载进去了，程序又可以正常访问了。

疑问：在配置多公众号的时候，是否可以动态加载数据库中配置新的公众号信息进来，Java服务不用重启？

感谢！

**Comment by binarywang** [comment]
自己想办法在更新数据库配置信息后，重新setMultiConfigStorages即可

**Comment by tangchangyuan** [comment]
请问解决了么?

**Comment by liangzhiyuan2015** [comment]
> 请问解决了么?

String appID = "XX";
WxMpDefaultConfigImpl configStorage = new WxMpDefaultConfigImpl();
configStorage.setAppId(appID);
configStorage.setSecret(appSecret);
// Map里加入新的WxMpConfigStorage,适用于动态添加新的微信公众号配置
wxService.addConfigStorage(appID, configStorage);

**Comment by tangchangyuan** [comment]
> > 请问解决了么?
> 
> String appID = "XX";
> String appSecret = "xx";
> WxMpDefaultConfigImpl configStorage = new WxMpDefaultConfigImpl();
> configStorage.setAppId(appID);
> configStorage.setSecret(appSecret);
> // Map里加入新的WxMpConfigStorage,适用于动态添加新的微信公众号配置
> wxService.addConfigStorage(appID, configStorage);

谢谢啦!!
