### ISSUE TITLE
放liunx服务器上部署，要放到tomcat下启动么，还是可以直接微服务启动？

### ISSUE THREAD

**Issue by ps2020** [binarywang/weixin-java-mp-demo-springboot#99]
打成jar包 放liunx服务器上部署，要放到tomcat下启动么，还是可以直接微服务启动？
为什么会报错 启动tomcat上下文报错
o.s.b.web.embedded.tomcat.TomcatStarter  :
 Error starting Tomcat context. Exception: org.springframework.beans.factory.BeanCreationException. 
 o.apache.catalina.core.StandardService   : Stopping service [Tomcat]

**Comment by binarywang** [comment]
关于spring boot 项目如何在tomcat下运行，网上有很多文章介绍

**Comment by ps2020** [comment]
可以不放在tomcat下启动吗

**Comment by binarywang** [comment]
> 可以不放在tomcat下启动吗

当然

**Comment by binarywang** [comment]
建议先去学习下spring boot相关基础

**Comment by ps2020** [comment]
好的，现在遇到的问题是在本地启动么得问题，放在liunx服务器上启动会报内置tomcat启动报错，在想是否是由于配置或者版本冲突导致的

**Comment by binarywang** [comment]
tomcat

> 好的，现在遇到的问题是在本地启动么得问题，放在liunx服务器上启动会报内置tomcat启动报错，在想是否是由于配置或者版本冲突导致的

tomcat上启动需要改配置，不是直接放上去就可以跑的，建议你现在本地测试完再放服务器上尝试

**Comment by ps2020** [comment]
服务器上没有使用tomcat ，是用nohup java -jar -Xms1024m -Xmx2048m ../wx.jar >/dev/null 2>&1 &微服务单独启动部署的，也需要改配置才可以吗

**Comment by binarywang** [comment]
> 服务器上没有使用tomcat ，是用nohup java -jar -Xms1024m -Xmx2048m ../wx.jar >/dev/null 2>&1 &微服务单独启动部署的，也需要改配置才可以吗

你是遇到问题了吗？是否尝试过，我理解是没问题的

**Comment by ps2020** [comment]
嗯遇到问题了，在尝试。你的意思是打成的jar包放到服务器上 以单个微服务启动部署 不需要再去改配置就可以运行了对吗？

**Comment by binarywang** [comment]
> 嗯遇到问题了，在尝试。你的意思是打成的jar包放到服务器上 以单个微服务启动部署 不需要再去改配置就可以运行了对吗？

没错，遇到问题在网上搜索就能解决了，很简单的
